### ISSUE TITLE
Unable to Login after removing twitter access

### ISSUE THREAD

**Issue by eladg** [OpenHunting/openhunt#15]
after seeing this: https://news.ycombinator.com/item?id=10760503
1. Remove twitter access 
   ![screen shot 2015-12-18 at 2 39 14 pm](https://cloud.githubusercontent.com/assets/1115533/11908883/2929859c-a595-11e5-97af-48cdcbb70bbd.png)
2. Log out.
3. Trying to login (login button then approve on twitter)
4. Callback failed with:

```
Login unsuccessful. Something went wrong: Error: api_calls exceeding plan authorized calls
```

**Comment by jacquescrocker** [comment]
looking at twitter docs, it resets after 15min. hmm, not sure how to get my rate limit increased. i'll look into it, maybe twitter will approve my request to support

**Comment by alanhamlett** [comment]
Is every request checking the OAuth token against the Twitter api or only on initial session creation?

**Comment by jacquescrocker** [comment]
@alanhamlett i think only on initial session creation

**Comment by NetOpWibby** [comment]
I am unable to login with Twitter, period. Are all the tokens used up?

**Comment by jacquescrocker** [comment]
@NetOperatorWibby yeah, sorry! we're looking into ways to fix this ASAP

**Comment by NetOpWibby** [comment]
@jacquescrocker I'm glad this project exists though, keep up the good work!

**Comment by railsjedi** [comment]
still working on fixing now. twitter auth was a really bad idea :( i regret that choice

no one can log in or do anything on the site

**Comment by railsjedi** [comment]
if anyone has any ideas on how to fix, let me know! 1) cache user lookups 2) add other auth types

**Comment by alanhamlett** [comment]
Facebook login?

**Comment by jacquescrocker** [comment]
ok, i am an idiot. it was oauth.io that was breaking

they wanted money. i paid them and now its good

sincere apologies!!

**Comment by eladg** [comment]
@jacquescrocker lol, yep, it works now.
