### ISSUE TITLE
Add a quick start READ ME guide

### ISSUE THREAD

**Issue by jkoech** [OpenHunting/openhunt#17]
Add a quick start READ ME guide to help noobs.

**Comment by nblackburn** [comment]
I have never touched ruby before this project but just about managed to get it working with 2.1.7 (_2.2.x seems to break it_).
- [Fork](https://github.com/OpenHunting/openhunt/fork) the repo.
- Install Ruby and Rails.
- Clone the repo `git clone https://github.com/OpenHunting/openhunt.git openhunt`.
- Add `gem 'tzinfo-data'` to Gemfile (_Fixes a timezone issue i had_).
- Run `ruby bin/bundle install`
- Renamed `settings.local.yml.sample` to `settings.local.yml`
- Registered a twitter application and added the keys to `settings.local.yml`.
- Run `ruby bin/rails server -b 127.0.0.1 -p 3000 -e development`
- Whalah!

Hopefully this helps.

**Comment by jacquescrocker** [comment]
https://github.com/OpenHunting/openhunt/blob/master/README.md

let me know if this works for you!
