### ISSUE TITLE
Can't access with JavaScript disabled

### ISSUE THREAD

**Issue by sheemeedah** [OpenHunting/openhunt#20]
I keep getting CAPTCHA if I have JavaScript disabled (was never successful in solving that, image or audio no matter).

I don't believe JavaScript is required for this site to work - with at least basic functionality. Could you please allow to access the site to browsers without JavaScript?

**Comment by jacquescrocker** [comment]
@sheemeedah thanks for the heads up. i'll fix the frontend so we don't require JS to use the site

**Comment by jacquescrocker** [comment]
@sheemeedah this should be fixed now, give it a try!
