### ISSUE TITLE
[BUG][FEATURE REQUEST] Login unsuccessful

### ISSUE THREAD

**Issue by Esqarrouth** [OpenHunting/openhunt#22]
Login unsuccessful. Something went wrong: Error: api_calls exceeding plan authorized calls

I like the idea, but you don't have to rip off everything. Twitter login? Just make it like reddit. Where you can be anonymous or just sign in with email. 

Facebook won the oauth war anyways, why even choose twitter..

**Comment by railsjedi** [comment]
agreed! twitter was bad idea

tracked via #15

**Comment by railsjedi** [comment]
fix now

**Comment by railsjedi** [comment]
fixed now

**Comment by jacquescrocker** [comment]
fixed now
