### ISSUE TITLE
Followers & Activity

### ISSUE THREAD

**Issue by akshaybharwani** [OpenHunting/openhunt#29]
1. Follow
2. Following and Followers
3. Notifications for actions of the users you follow.

**Comment by akshaybharwani** [comment]
And also a feature where a user can verify if a product is already listed or not.

**Comment by nblackburn** [comment]
I agree with every single suggestion but feel they should be kept separate (to keep everything organised).

**Comment by jacquescrocker** [comment]
i wouldn't want to implement a custom activity feed, however I'd be interested in reusing something like this: https://getstream.io/
