### ISSUE TITLE
Join us on Github link is broken

### ISSUE THREAD

**Issue by andyzg** [OpenHunting/openhunt#3]
https://www.openhunt.co/people
Links to github/openhunting/openhunt instead of github.com/openhunting/openhunt

**Comment by frewsxcv** [comment]
It looks like that file hasn't been pushed to github

https://github.com/OpenHunting/openhunt/blob/master/app/views/pages/people.html.haml

**Comment by jacquescrocker** [comment]
fixed via b75782433749d80050a822dc84f40ab84400bc5b 

thanks for the heads up!

**Comment by frewsxcv** [comment]
At the time of writing, that's not a valid commit hash:

https://github.com/OpenHunting/openhunt/commit/b75782433749d80050a822dc84f40ab84400bc5b

**Comment by jacquescrocker** [comment]
oops, my mistake. fixed now!

**Comment by frewsxcv** [comment]
Just got pushed. THanks!
