### ISSUE TITLE
(Not) Completing Login...

### ISSUE THREAD

**Issue by rossgeesman** [OpenHunting/openhunt#31]
Logged in once on my phone then later tried from my notebook and authorization hangs up at https://www.openhunt.co/login/callback. 

PS i think this is a great idea. Lack of openness at PH has always rubbed me the wrong way.

**Comment by ppanthony** [comment]
[Error] TypeError: undefined is not an object (evaluating 'OAuth.callback('twitter')
  .done')
    global code (callback, line 43)

Are you using Safari by any chance?

**Comment by jacquescrocker** [comment]
i think i know the issue, should be fixed soon

we're using a 3rd party oauth handler service and safari might be blocking the js. ill switch it out with omniauth (ruby library) and this should go away.

thanks for the heads up!

**Comment by rossgeesman** [comment]
@ppanthony @jacquescrocker Yes! Just logged in successfully in Chrome.

**Comment by jacquescrocker** [comment]
ok, this should be fixed now! please reopen this issue if it occurs again
