### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by jacquescrocker** [OpenHunting/openhunt#32]

**Comment by nblackburn** [comment]
+1

**Comment by pwlin** [comment]
+1

**Comment by iliaznk** [comment]
+1

**Comment by mbajur** [comment]
Any feedback on how can you imagine such feed? We can basically create a separate feeds for various scopes (currently i can think of two scopes: recently added and top posts)
- **/recent.rss(.atom)** - 25(?) recently posted projects
- **/popular.rss(.atom)** - 25(?) most popular projects - but in what time scope? current day (bucket)? week? month? all the time? What you guys think?

**Comment by mbajur** [comment]
Ok, i have made it like this:
- **/recent.rss(.atom)** - 25 recently posted projects
- **/popular.rss(.atom)** - 25 most popular projects this day

If you think that should be improved in any way, feel free to write about it.

**Comment by pwlin** [comment]
That's really great @mbajur Thank you very much!
It is probably me, but I don't see where you committed ATOM's `<link />` tag inside an entry.

[`app/views/projects/_project.atom.jbuilder`](https://github.com/OpenHunting/openhunt/blob/ec34aebec5a9e4e969caedd837f600ca44e62b11/app/views/projects/_project.atom.jbuilder) does not have an `entry.link` reference. 

Or am I missing something?

**Comment by mbajur** [comment]
That's handled by this line (`url` param):

https://github.com/OpenHunting/openhunt/blob/master/app/views/projects/_project.atom.jbuilder#L1

**Comment by pwlin** [comment]
OK Great, I knew it was me :) Thanks.
