### ISSUE TITLE
Better Readability of text

### ISSUE THREAD

**Issue by jacquescrocker** [OpenHunting/openhunt#33]
as mentioned by many people, gray on white is not a great combination :(

**Comment by nblackburn** [comment]
It depends on the shade of grey, but if you are referring to the descriptions then i agree and would go for a darker shade like #888888

**Comment by edisonchee** [comment]
I would look into other elements of typography as well. Right now the root font size is 10px which makes the description's font size of 12px (1.2rem) too small to read on desktop devices. I would really recommend at least 14px or more, depending on your baseline grid.

**Comment by nblackburn** [comment]
@edisonchee Agreed, 14px is the minimum baseline for most browsers and would help with legibility especially for people with visual impairment.

**Comment by speizerj** [comment]
Gray on white can definitely work well, but it needs to be done right. I think as @edisonchee and @nblackburn have already said, increasing the font size and darkening it a bit would be very beneficial. I also think that reducing the font-weight on the body font and perhaps moving to a serif font would provide the most gains in readability. I'll mess around with a few combinations and post some screenshots

**Comment by chrishcode** [comment]
![whitespace](https://cloud.githubusercontent.com/assets/8015326/11915396/404455ca-a6a5-11e5-832b-cd1224e88ed3.png)
I think adding a bit of whitespace, darkening color and increasing the font size on the description text like this makes it more readable.

**Comment by nblackburn** [comment]
@chriswohlfarth I feel there is too much white space between the projects, perhaps try shaving 10px off and see how it looks.

**Comment by chrishcode** [comment]
@nblackburn You might be right, I guess it's a matter of preference.

**Comment by ys-chung** [comment]
Also, [Montserrat](https://www.kickstarter.com/projects/julietaulanovsky/the-montserrat-typeface) is modelled after historical signage, made for title and not small text. The text under the product names could perhaps use a different font.

**Comment by edisonchee** [comment]
Made a minor tweak to description text color, and fixed a slight layout issue where .item-vote was clipped due to parent having overflow:hidden.

Also applied a border-radius, transition and alignment for the entire button, so that it's more obvious when you mouseover the vote button.

**Comment by jacquescrocker** [comment]
i applied @edisonchee's changes and deployed. let me know what you think!

closing this issue for now but i can reopen it if anyone thinks it needs further tuning
