### ISSUE TITLE
Local instance of openhunt not logging in

### ISSUE THREAD

**Issue by kiriappeee** [OpenHunting/openhunt#36]
After cloning app to local machine, running rails server, and then following instructions to add all the missing pieces (gem bundle install, creation of db, db migration, and adding my own settings.local.yml file), I got the app running at localhost:3000.

Tried to login and it goes to twitter, authenticates, redirects back to the application and after spending a few seconds on localhost:3000/login/callback# it changes the message from logging in to Login unsuccessful. Something went wrong.

Would really be grateful for some direction in where to go from here to make the app work :) 

Thanks!!

**Comment by nblackburn** [comment]
References #17.

**Comment by speizerj** [comment]
Having same issue as @kiriappeee here - I'm wondering if it has to do with the twitter key/secret. I'm getting a 500 error when trying to access /success with the following response: Twitter::Error::Unauthorized in SessionsController#auth_success

**Comment by jacquescrocker** [comment]
im switching out oauth to use omniauth. ill get that checked in soon and
some instructions on the README on how to set up the twitter app for dev

**Comment by speizerj** [comment]
Awesome, thanks @jacquescrocker

**Comment by kiriappeee** [comment]
Brilliant. Looking forward to it :). :+1:

**Comment by jacquescrocker** [comment]
give this a try! https://github.com/OpenHunting/openhunt/blob/master/README.md

**Comment by speizerj** [comment]
@jacquescrocker I'm getting this error after following your instructions:

https://www.dropbox.com/s/6vhpiqp4tzixolw/Screenshot%202015-12-20%2013.04.22.png?dl=0

**Comment by nblackburn** [comment]
@speizerj The twitter API is throttled, the last time i checked, you can make 15 requests per 15mins. The message you are getting means you have exceeded this limitation and will need to wait for it to enter the next window to reset.

**Comment by speizerj** [comment]
@nblackburn This was on the first request though. I deleted my comment because I just needed to pull in the latest from master - it's working now. Thanks
