### ISSUE TITLE
"About" Modal Window needs a "X" closing icon

### ISSUE THREAD

**Issue by tripad** [OpenHunting/openhunt#40]
The about modal window opens automatically currently even on mobile browsers. It is kind of tricky to tap between the space of the container and window to close it.

**Comment by nblackburn** [comment]
The logic exists so it's simply a case of adding a link with a class of `.close-about`.

**Comment by nblackburn** [comment]
There are two implementations of this fix open, one being a mobile friendly link (#41) and the other a "x" button (#46).
