### ISSUE TITLE
Install and setup instructions

### ISSUE THREAD

**Issue by vaMuchenje** [OpenHunting/openhunt#43]
I want to contribute to the project but I don't know where the install instructions are. Perhaps someone who has forked and setup a local install can do a quick write up.

**Comment by nblackburn** [comment]
See #17

**Comment by nblackburn** [comment]
I have never touched ruby before this project but just about managed to get it working with 2.1.7 (2.2.x seems to break it).

- `ruby bin/bundle install`
- `ruby bin/rails server -b 127.0.0.1 -p 3000 -e development`

**Comment by jacquescrocker** [comment]
@vaMuchenje just added, can you give it a try? https://github.com/OpenHunting/openhunt/blob/master/README.md

thanks!
