### ISSUE TITLE
What's your code of conduct?

### ISSUE THREAD

**Issue by alison985** [OpenHunting/openhunt#47]
Hi,

I'm just curious what your code of conduct is for this project?

Thanks,
Alison

**Comment by nblackburn** [comment]
At the moment there isn't really one but would recommend that change once traction is gained. The best way of tackling this is by creating a `contributing.md` file on the repo which GitHub will detect and recommend when making commits as a guideline for code conventions etc...

**Comment by jacquescrocker** [comment]
agreed! should we just steal a `contributing.md` from another well run open source project? :)

ember, rails, etc. one of those

**Comment by jacquescrocker** [comment]
this seems really good: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md

and https://github.com/emberjs/ember.js/blob/master/CODE_OF_CONDUCT.md 

http://emberjs.com/guidelines/

**Comment by jacquescrocker** [comment]
https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md is good too (ember i think shares a lot of the same content)

**Comment by nblackburn** [comment]
@jacquescrocker I am actually in the process of drafting one up now on my fork of the repo.
