### ISSUE TITLE
projects index only gets 'today', repeatedly

### ISSUE THREAD

**Issue by mhurwi** [OpenHunting/openhunt#50]
the projects index page is only displaying 'today' and no other days, it continually tries to GET the same date bucket.

**Comment by http-teapot** [comment]
It prevents me from using the product, can that be fixed soon?

**Comment by jacquescrocker** [comment]
deploying fix shortly

**Comment by jacquescrocker** [comment]
ok, fixed and deployed. thanks @mhurwi for the fix!
