### ISSUE TITLE
Saturday products don't show in the list

### ISSUE THREAD

**Issue by http-teapot** [OpenHunting/openhunt#57]
This [line](https://github.com/OpenHunting/openhunt/blob/master/app/models/project.rb#L136) explicitly says "If today is Sunday (first day of week) then previous date is Friday" which effectively prevents the JS from loading yesterday's products. Is that voluntary? Maybe add a comment?

**Comment by http-teapot** [comment]
It seems that today's products are yesterday's products. I didn't upvote anything today yet the top products are the one I voted for yesterday.

**Comment by jacquescrocker** [comment]
yeah, it's not super clear. i'll add better messaging

the idea is we have a "weekend edition", so sat/sun is grouped together

possibly a bad idea, but that was the idea :)

**Comment by http-teapot** [comment]
I think it's a great idea because activity will be at its lowest during the weekend but in the current implementation posting a product early Saturday will give a tremendous advantage over posting a product on Sunday. Maybe that's ok? I agree it needs better messaging, now that you explained it makes more sense, thanks! :100: :+1:

**Comment by http-teapot** [comment]
Quick code review: one caveat in the current design is that there are [date calculation](https://github.com/OpenHunting/openhunt/blob/master/app/models/project.rb#L103-L131) which may [skew your data](https://github.com/OpenHunting/openhunt/blob/master/app/models/project.rb#L49) and may prevent you in the future to change how you handle the list. For instance - if I understood properly - if you decide to separate Saturday from Sunday it appears that Saturday product bucket will be set to Sunday which means Saturday's list will be empty.

I'd apply that logic on the way out (controller/view logic), for instance:

Controller logic:

```
if bucket is Sunday then query(now and now - 1.day)
else query(now)
```

View logic:

```
if bucket is Saturday or Sunday then display "Weekend edition"
else display "Today"
```

P.S. I might be completely wrong

**Comment by jacquescrocker** [comment]
added some better titling

I agree about the issue with having an advantage submitting earlier rather than later. It might be solved with "Queueing" support (#59)

**Comment by jacquescrocker** [comment]
@http-teapot we use the datebucket on the project, however we still have the created_at date so we could recalculate date bucket

**Comment by jacquescrocker** [comment]
deployed now, thanks for head up on this bug!
