### ISSUE TITLE
Gitter Chat

### ISSUE THREAD

**Issue by rmcfadzean** [OpenHunting/openhunt#58]
Would be excellent to have a place to talk in real-ish time with other contributors.

https://gitter.im/

**Comment by nblackburn** [comment]
Great idea to have a place to hangout, also there is [Slack](http://slack.com) too.

**Comment by rmcfadzean** [comment]
Would be ok with IRC too. #OpenHunt on freenode?

**Comment by mbajur** [comment]
+1 for gitter, it does not involves creating an account (cause it's based on github, we're all using github anyway), it's deeply integrated with github and supports embedding chat directly on a website in a side panel.

**Comment by jacquescrocker** [comment]
gitter is now set up! https://gitter.im/OpenHunting/openhunt
