### ISSUE TITLE
How to access comments

### ISSUE THREAD

**Issue by berpj** [OpenHunting/openhunt#63]
I may be missing something, but I don't understand how I can access to the comments posted on my product, even if there is written "All comments go directly to the product owner, and aren't posted publicly".

Where are they posted?

Thanks!

**Comment by nblackburn** [comment]
As far as i am aware, it's in the works but not actually implemented as of this version.

**Comment by jacquescrocker** [comment]
project submitters can now access the comments.

this causes some issues around who is actually the product owner, tracked via #73
