### ISSUE TITLE
Move email address from list_subscribers

### ISSUE THREAD

**Issue by nblackburn** [OpenHunting/openhunt#82]
![email_field](https://cloud.githubusercontent.com/assets/2931085/11944620/5577c3dc-a83f-11e5-9e82-7433cf05b25f.png)

I feel it would be better to remove the `email` field from `list_subsribers` to `users` to keep everything uniform.

**Comment by jacquescrocker** [comment]
yeah, its a little weird. the idea was that people should be able to subscribe to the list without necessarily signing in. and then once they sign in, it'll associate that list subscriber to the user

**Comment by nblackburn** [comment]
I see, but for the website think it would be better getting people to signup then we can create personalised emails instead of generic ones.

**Comment by jacquescrocker** [comment]
personalized emails sounds hard :) machine learning?

just getting them the top voted products of the day seems like it'd be enough. if someones on the list, i think it wont be hard to get them to sign up since the actions on the email (like upvote / comment) will send them through the login flow

**Comment by nblackburn** [comment]
Eeek! not at all, i simply mean being able to address people by name.

```
Hey Nathaniel,

Here are today's top picks for you...
```

**Comment by jacquescrocker** [comment]
ah, i see. 

if we have the user id, i think it makes sense to address them by name. but not enough to require sign up in order to get the emails

**Comment by nblackburn** [comment]
I see your point but part of me wants people to sign up.

Closing for now as it's a bit of grey area.
