### ISSUE TITLE
database.yml.example

### ISSUE THREAD

**Issue by izaban** [OpenHunting/openhunt#87]
Should we use a database.yml.example file and add database.yml to .gitignore? or there is another approach? if there is, maybe it can be explained it in the README.md

**Comment by jacquescrocker** [comment]
yep, there's another approach now

http://edgeguides.rubyonrails.org/configuring.html#configuring-a-database

you can override the database connection using DATABASE_URL env variable

i'll update the README to make a note of this

**Comment by jacquescrocker** [comment]
updated README with instructions, let me know if it still has issues for you and i'll reopen this ticket

thanks!
