### ISSUE TITLE
New product modal

### ISSUE THREAD

**Issue by nblackburn** [OpenHunting/openhunt#98]
I have been toying with the idea of making the new product page a modal, what are your thoughts on this?.

![modal](https://cloud.githubusercontent.com/assets/2931085/12174693/2264e14a-b556-11e5-9ba1-4d0d597e6560.png)

**Comment by jacquescrocker** [comment]
my vote would be to leave it as a separate page. easier / cleaner, and its linkable

**Comment by nblackburn** [comment]
@ja

**Comment by nblackburn** [comment]
@jacquescrocker I decided against it not long after posting but do feel it could be improved.
